add build_rvxy (Revancify Yellow Icon) (Experimental)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -323,8 +323,114 @@ jobs:
          skip_checkout: false
          file_pattern: build_rvxr.md *-rvxr-update.json
          commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+    
+build_rvxy:
+  #  needs: build_rvxy
+   runs-on: ubuntu-latest
+   steps:
+     - name: Checkout
+       uses: actions/checkout@v4
+       with:
+         fetch-depth: 0
+         submodules: true
+
+     - name: Set up Java
+       uses: actions/setup-java@v4
+       with:
+         distribution: "zulu"
+         java-version: "17"
+
+     - name: Update config
+       if: ${{ inputs.from_ci }}
+       run: |
+         if git checkout origin/update build_rvxy.md; then
+           UPDATE_CFG=$(./build.sh config_rvxy.toml --config-update)
+           if [ "$UPDATE_CFG" ]; then
+             echo "$UPDATE_CFG" > config_rvxy.toml
+           fi
+         fi
+
+     - name: Get next version code
+       id: next_ver_code
+       env:
+         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       run: |
+         TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
+         if [ -z "$TAG" ]; then TAG=0; fi
+         echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
+
+     - name: Build modules/APKs
+       run: ./build.sh config_rvxy.toml rvxy options_rvxy.json
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         GITHUB_REPOSITORY: ${{ github.repository }}
+         NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+     - name: Get output
+       id: get_output
+       run: |
+         DELIM="$(openssl rand -hex 8)"
+         echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+         cat build.md >> "$GITHUB_OUTPUT"
+         echo "${DELIM}" >> "$GITHUB_OUTPUT"
+         cp -f build.md build_rvxy.tmp
+
+     - run: sleep 30
+
+     - name: Upload modules to release
+       uses: svenstaro/upload-release-action@v2
+       with:
+         body: ${{ steps.get_output.outputs.BUILD_LOG }}
+         repo_token: ${{ secrets.GITHUB_TOKEN }}
+         file: ./build/*
+         tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+         file_glob: true
+         overwrite: true
+
+     - name: Update changelog and Magisk update json
+       id: update_config
+       run: |
+         git checkout -f update || git switch --discard-changes --orphan update
+         cp -f build_rvxy.tmp build_rvxy.md
+         get_update_json() {
+           echo "{
+           \"version\": \"$1\",
+           \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+           \"zipUrl\": \"$2\",
+           \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build_rvxy.md\"
+         }"
+         }
+
+         cd build || { echo "build folder not found"; exit 1; }
+         for OUTPUT in *magisk*.zip; do
+           [ "$OUTPUT" = "*magisk*.zip" ] && continue
+           ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+           if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+           UPDATE_JSON="${UPDATE_JSON##*/}"
+           VER=$(echo "$ZIP_S" | grep version=)
+           VER="${VER##*=}"
+           DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+           get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+         done
+         cd ..
+
+         find . -name "*-rvxy-update.json" | grep . || : >dummy-update.json
+
+     - name: Update git
+       run: |
+         git fetch origin update
+         git pull origin update
+
+     - uses: stefanzweifel/git-auto-commit-action@v5
+       with:
+         branch: update
+         skip_fetch: false
+         skip_checkout: false
+         file_pattern: build_rvxy.md *-rvxy-update.json
+         commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}    
+ 
  build_rvxab:
-  #  needs: build_rvxr
+  #  needs: build_rvxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
@@ -374,7 +480,7 @@ jobs:
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build_rvxab.tmp
 
-     - run: sleep 30
+     - run: sleep 40
 
      - name: Upload modules to release
        uses: svenstaro/upload-release-action@v2
@@ -478,7 +584,7 @@ jobs:
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build_rvxar.tmp
 
-     - run: sleep 45
+     - run: sleep 55
 
      - name: Upload modules to release
        uses: svenstaro/upload-release-action@v2
@@ -582,7 +688,7 @@ jobs:
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build_rvxm.tmp
 
-     - run: sleep 50
+     - run: sleep 60
 
      - name: Upload modules to release
        uses: svenstaro/upload-release-action@v2
