Added MMT Blue, Green, Yellow (Experimental)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -686,7 +686,7 @@ jobs:
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          cp -f build.md build_rvxm.tmp
 
-     - run: sleep 60
+     - run: sleep 65
 
      - name: Upload modules to release
        uses: svenstaro/upload-release-action@v2
@@ -739,7 +739,318 @@ jobs:
         skip_checkout: false
         file_pattern: build_rvxm.md *-rvxm-update.json
         commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
-  
+build_rvxmb:
+  #  needs: build_rvxm
+   runs-on: ubuntu-latest
+   steps:
+     - name: Checkout
+       uses: actions/checkout@v4
+       with:
+         fetch-depth: 0
+         submodules: true
+
+     - name: Set up Java
+       uses: actions/setup-java@v4
+       with:
+         distribution: "zulu"
+         java-version: "17"
+
+     - name: Update config
+       if: ${{ inputs.from_ci }}
+       run: |
+         if git checkout origin/update build_rvxmb.md; then
+           UPDATE_CFG=$(./build.sh config_rvxmb.toml --config-update)
+           if [ "$UPDATE_CFG" ]; then
+             echo "$UPDATE_CFG" > config_rvxmb.toml
+           fi
+         fi
+
+     - name: Get next version code
+       id: next_ver_code
+       env:
+         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       run: |
+         TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
+         if [ -z "$TAG" ]; then TAG=0; fi
+         echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
+
+     - name: Build modules/APKs
+       run: ./build.sh config_rvxmb.toml rvxmb options_rvxmb.json
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         GITHUB_REPOSITORY: ${{ github.repository }}
+         NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+     - name: Get output
+       id: get_output
+       run: |
+         DELIM="$(openssl rand -hex 8)"
+         echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+         cat build.md >> "$GITHUB_OUTPUT"
+         echo "${DELIM}" >> "$GITHUB_OUTPUT"
+         cp -f build.md build_rvxmb.tmp
+
+     - run: sleep 75
+
+     - name: Upload modules to release
+       uses: svenstaro/upload-release-action@v2
+       with:
+         body: ${{ steps.get_output.outputs.BUILD_LOG }}
+         repo_token: ${{ secrets.GITHUB_TOKEN }}
+         file: ./build/*
+         tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+         file_glob: true
+         overwrite: true
+
+     - name: Update changelog and Magisk update json
+       id: update_config
+       run: |
+         git checkout -f update || git switch --discard-changes --orphan update
+         cp -f build_rvxmb.tmp build_rvxmb.md
+         get_update_json() {
+           echo "{
+           \"version\": \"$1\",
+           \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+           \"zipUrl\": \"$2\",
+           \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build_rvxmb.md\"
+         }"
+         }
+
+         cd build || { echo "build folder not found"; exit 1; }
+         for OUTPUT in *magisk*.zip; do
+           [ "$OUTPUT" = "*magisk*.zip" ] && continue
+           ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+           if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+           UPDATE_JSON="${UPDATE_JSON##*/}"
+           VER=$(echo "$ZIP_S" | grep version=)
+           VER="${VER##*=}"
+           DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+           get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+         done
+         cd ..
+
+         find . -name "*-rvxmb-update.json" | grep . || : >dummy-update.json
+
+     - name: Update git
+       run: |
+         git fetch origin update
+         git pull origin update
+    
+     - uses: stefanzweifel/git-auto-commit-action@v5
+       with:
+        branch: update
+        skip_fetch: false
+        skip_checkout: false
+        file_pattern: build_rvxmb.md *-rvxmb-update.json
+        commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+build_rvxmg:
+  #  needs: build_rvxmb
+   runs-on: ubuntu-latest
+   steps:
+     - name: Checkout
+       uses: actions/checkout@v4
+       with:
+         fetch-depth: 0
+         submodules: true
+
+     - name: Set up Java
+       uses: actions/setup-java@v4
+       with:
+         distribution: "zulu"
+         java-version: "17"
+
+     - name: Update config
+       if: ${{ inputs.from_ci }}
+       run: |
+         if git checkout origin/update build_rvxmg.md; then
+           UPDATE_CFG=$(./build.sh config_rvxmg.toml --config-update)
+           if [ "$UPDATE_CFG" ]; then
+             echo "$UPDATE_CFG" > config_rvxmg.toml
+           fi
+         fi
+
+     - name: Get next version code
+       id: next_ver_code
+       env:
+         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       run: |
+         TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
+         if [ -z "$TAG" ]; then TAG=0; fi
+         echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
+
+     - name: Build modules/APKs
+       run: ./build.sh config_rvxmg.toml rvxmg options_rvxmg.json
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         GITHUB_REPOSITORY: ${{ github.repository }}
+         NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+     - name: Get output
+       id: get_output
+       run: |
+         DELIM="$(openssl rand -hex 8)"
+         echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+         cat build.md >> "$GITHUB_OUTPUT"
+         echo "${DELIM}" >> "$GITHUB_OUTPUT"
+         cp -f build.md build_rvxmg.tmp
+
+     - run: sleep 85
+
+     - name: Upload modules to release
+       uses: svenstaro/upload-release-action@v2
+       with:
+         body: ${{ steps.get_output.outputs.BUILD_LOG }}
+         repo_token: ${{ secrets.GITHUB_TOKEN }}
+         file: ./build/*
+         tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+         file_glob: true
+         overwrite: true
+
+     - name: Update changelog and Magisk update json
+       id: update_config
+       run: |
+         git checkout -f update || git switch --discard-changes --orphan update
+         cp -f build_rvxmg.tmp build_rvxmg.md
+         get_update_json() {
+           echo "{
+           \"version\": \"$1\",
+           \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+           \"zipUrl\": \"$2\",
+           \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build_rvxmg.md\"
+         }"
+         }
+
+         cd build || { echo "build folder not found"; exit 1; }
+         for OUTPUT in *magisk*.zip; do
+           [ "$OUTPUT" = "*magisk*.zip" ] && continue
+           ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+           if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+           UPDATE_JSON="${UPDATE_JSON##*/}"
+           VER=$(echo "$ZIP_S" | grep version=)
+           VER="${VER##*=}"
+           DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+           get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+         done
+         cd ..
+
+         find . -name "*-rvxmg-update.json" | grep . || : >dummy-update.json
+
+     - name: Update git
+       run: |
+         git fetch origin update
+         git pull origin update
+    
+     - uses: stefanzweifel/git-auto-commit-action@v5
+       with:
+        branch: update
+        skip_fetch: false
+        skip_checkout: false
+        file_pattern: build_rvxmg.md *-rvxmg-update.json
+        commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+build_rvxmy:
+  #  needs: build_rvxmg
+   runs-on: ubuntu-latest
+   steps:
+     - name: Checkout
+       uses: actions/checkout@v4
+       with:
+         fetch-depth: 0
+         submodules: true
+
+     - name: Set up Java
+       uses: actions/setup-java@v4
+       with:
+         distribution: "zulu"
+         java-version: "17"
+
+     - name: Update config
+       if: ${{ inputs.from_ci }}
+       run: |
+         if git checkout origin/update build_rvxmy.md; then
+           UPDATE_CFG=$(./build.sh config_rvxmy.toml --config-update)
+           if [ "$UPDATE_CFG" ]; then
+             echo "$UPDATE_CFG" > config_rvxmy.toml
+           fi
+         fi
+
+     - name: Get next version code
+       id: next_ver_code
+       env:
+         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       run: |
+         TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
+         if [ -z "$TAG" ]; then TAG=0; fi
+         echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
+
+     - name: Build modules/APKs
+       run: ./build.sh config_rvxmy.toml rvxmy options_rvxmy.json
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         GITHUB_REPOSITORY: ${{ github.repository }}
+         NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+     - name: Get output
+       id: get_output
+       run: |
+         DELIM="$(openssl rand -hex 8)"
+         echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+         cat build.md >> "$GITHUB_OUTPUT"
+         echo "${DELIM}" >> "$GITHUB_OUTPUT"
+         cp -f build.md build_rvxmy.tmp
+
+     - run: sleep 95
+
+     - name: Upload modules to release
+       uses: svenstaro/upload-release-action@v2
+       with:
+         body: ${{ steps.get_output.outputs.BUILD_LOG }}
+         repo_token: ${{ secrets.GITHUB_TOKEN }}
+         file: ./build/*
+         tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+         file_glob: true
+         overwrite: true
+
+     - name: Update changelog and Magisk update json
+       id: update_config
+       run: |
+         git checkout -f update || git switch --discard-changes --orphan update
+         cp -f build_rvxmy.tmp build_rvxmy.md
+         get_update_json() {
+           echo "{
+           \"version\": \"$1\",
+           \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+           \"zipUrl\": \"$2\",
+           \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build_rvxmy.md\"
+         }"
+         }
+
+         cd build || { echo "build folder not found"; exit 1; }
+         for OUTPUT in *magisk*.zip; do
+           [ "$OUTPUT" = "*magisk*.zip" ] && continue
+           ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+           if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+           UPDATE_JSON="${UPDATE_JSON##*/}"
+           VER=$(echo "$ZIP_S" | grep version=)
+           VER="${VER##*=}"
+           DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+           get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+         done
+         cd ..
+
+         find . -name "*-rvxmy-update.json" | grep . || : >dummy-update.json
+
+     - name: Update git
+       run: |
+         git fetch origin update
+         git pull origin update
+    
+     - uses: stefanzweifel/git-auto-commit-action@v5
+       with:
+        branch: update
+        skip_fetch: false
+        skip_checkout: false
+        file_pattern: build_rvxmy.md *-rvxmy-update.json
+        commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}        
  build_rvx_reddit:
    runs-on: ubuntu-latest
    steps:
