как же надоели новые иконки анддеа делай их поменьше пж (ч2)
Add jobs to build new MMT icons

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1052,7 +1052,319 @@ jobs:
         skip_fetch: false
         skip_checkout: false
         file_pattern: build_rvxmy.md *-rvxmy-update.json
+        commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+ build_rvxmo:
+  #  needs: build_rvxmy
+      runs-on: ubuntu-latest
+   steps:
+     - name: Checkout
+       uses: actions/checkout@v4
+       with:
+         fetch-depth: 0
+         submodules: true
+
+     - name: Set up Java
+       uses: actions/setup-java@v4
+       with:
+         distribution: "zulu"
+         java-version: "17"
+
+     - name: Update config
+       if: ${{ inputs.from_ci }}
+       run: |
+         if git checkout origin/update build_rvxmo.md; then
+           UPDATE_CFG=$(./build.sh config_rvxmo.toml --config-update)
+           if [ "$UPDATE_CFG" ]; then
+             echo "$UPDATE_CFG" > config_rvxmo.toml
+           fi
+         fi
+
+     - name: Get next version code
+       id: next_ver_code
+       env:
+         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       run: |
+         TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
+         if [ -z "$TAG" ]; then TAG=0; fi
+         echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
+
+     - name: Build modules/APKs
+       run: ./build.sh config_rvxmo.toml rvxmo options_rvxmo.json
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         GITHUB_REPOSITORY: ${{ github.repository }}
+         NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+     - name: Get output
+       id: get_output
+       run: |
+         DELIM="$(openssl rand -hex 8)"
+         echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+         cat build.md >> "$GITHUB_OUTPUT"
+         echo "${DELIM}" >> "$GITHUB_OUTPUT"
+         cp -f build.md build_rvxmo.tmp
+
+     - run: sleep 220
+
+     - name: Upload modules to release
+       uses: svenstaro/upload-release-action@v2
+       with:
+         body: ${{ steps.get_output.outputs.BUILD_LOG }}
+         repo_token: ${{ secrets.GITHUB_TOKEN }}
+         file: ./build/*
+         tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+         file_glob: true
+         overwrite: true
+
+     - name: Update changelog and Magisk update json
+       id: update_config
+       run: |
+         git checkout -f update || git switch --discard-changes --orphan update
+         cp -f build_rvxmo.tmp build_rvxmo.md
+         get_update_json() {
+           echo "{
+           \"version\": \"$1\",
+           \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+           \"zipUrl\": \"$2\",
+           \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build_rvxmo.md\"
+         }"
+         }
+
+         cd build || { echo "build folder not found"; exit 1; }
+         for OUTPUT in *magisk*.zip; do
+           [ "$OUTPUT" = "*magisk*.zip" ] && continue
+           ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+           if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+           UPDATE_JSON="${UPDATE_JSON##*/}"
+           VER=$(echo "$ZIP_S" | grep version=)
+           VER="${VER##*=}"
+           DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+           get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+         done
+         cd ..
+
+         find . -name "*-rvxmo-update.json" | grep . || : >dummy-update.json
+
+     - name: Update git
+       run: |
+         git fetch origin update
+         git pull origin update
+    
+     - uses: stefanzweifel/git-auto-commit-action@v5
+       with:
+        branch: update
+        skip_fetch: false
+        skip_checkout: false
+        file_pattern: build_rvxmo.md *-rvxmo-update.json
         commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}        
+ build_rvxmp:
+  #  needs: build_rvxmo
+      runs-on: ubuntu-latest
+   steps:
+     - name: Checkout
+       uses: actions/checkout@v4
+       with:
+         fetch-depth: 0
+         submodules: true
+
+     - name: Set up Java
+       uses: actions/setup-java@v4
+       with:
+         distribution: "zulu"
+         java-version: "17"
+
+     - name: Update config
+       if: ${{ inputs.from_ci }}
+       run: |
+         if git checkout origin/update build_rvxmp.md; then
+           UPDATE_CFG=$(./build.sh config_rvxmp.toml --config-update)
+           if [ "$UPDATE_CFG" ]; then
+             echo "$UPDATE_CFG" > config_rvxmp.toml
+           fi
+         fi
+
+     - name: Get next version code
+       id: next_ver_code
+       env:
+         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       run: |
+         TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
+         if [ -z "$TAG" ]; then TAG=0; fi
+         echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
+
+     - name: Build modules/APKs
+       run: ./build.sh config_rvxmp.toml rvxmp options_rvxmp.json
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         GITHUB_REPOSITORY: ${{ github.repository }}
+         NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+     - name: Get output
+       id: get_output
+       run: |
+         DELIM="$(openssl rand -hex 8)"
+         echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+         cat build.md >> "$GITHUB_OUTPUT"
+         echo "${DELIM}" >> "$GITHUB_OUTPUT"
+         cp -f build.md build_rvxmp.tmp
+
+     - run: sleep 240
+
+     - name: Upload modules to release
+       uses: svenstaro/upload-release-action@v2
+       with:
+         body: ${{ steps.get_output.outputs.BUILD_LOG }}
+         repo_token: ${{ secrets.GITHUB_TOKEN }}
+         file: ./build/*
+         tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+         file_glob: true
+         overwrite: true
+
+     - name: Update changelog and Magisk update json
+       id: update_config
+       run: |
+         git checkout -f update || git switch --discard-changes --orphan update
+         cp -f build_rvxmp.tmp build_rvxmp.md
+         get_update_json() {
+           echo "{
+           \"version\": \"$1\",
+           \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+           \"zipUrl\": \"$2\",
+           \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build_rvxmp.md\"
+         }"
+         }
+
+         cd build || { echo "build folder not found"; exit 1; }
+         for OUTPUT in *magisk*.zip; do
+           [ "$OUTPUT" = "*magisk*.zip" ] && continue
+           ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+           if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+           UPDATE_JSON="${UPDATE_JSON##*/}"
+           VER=$(echo "$ZIP_S" | grep version=)
+           VER="${VER##*=}"
+           DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+           get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+         done
+         cd ..
+
+         find . -name "*-rvxmp-update.json" | grep . || : >dummy-update.json
+
+     - name: Update git
+       run: |
+         git fetch origin update
+         git pull origin update
+    
+     - uses: stefanzweifel/git-auto-commit-action@v5
+       with:
+        branch: update
+        skip_fetch: false
+        skip_checkout: false
+        file_pattern: build_rvxmp.md *-rvxmp-update.json
+        commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+ build_rvxmt:
+  #  needs: build_rvxmo
+    runs-on: ubuntu-latest
+       steps:
+         - name: Checkout
+           uses: actions/checkout@v4
+           with:
+             fetch-depth: 0
+             submodules: true
+
+         - name: Set up Java
+           uses: actions/setup-java@v4
+           with:
+             distribution: "zulu"
+             java-version: "17"
+
+         - name: Update config
+           if: ${{ inputs.from_ci }}
+           run: |
+             if git checkout origin/update build_rvxmt.md; then
+               UPDATE_CFG=$(./build.sh config_rvxmt.toml --config-update)
+               if [ "$UPDATE_CFG" ]; then
+                 echo "$UPDATE_CFG" > config_rvxmt.toml
+               fi
+             fi
+
+         - name: Get next version code
+           id: next_ver_code
+           env:
+             GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+           run: |
+             TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
+             if [ -z "$TAG" ]; then TAG=0; fi
+             echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
+
+         - name: Build modules/APKs
+           run: ./build.sh config_rvxmt.toml rvxmt options_rvxmt.json
+           env:
+             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+             GITHUB_REPOSITORY: ${{ github.repository }}
+             NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+
+         - name: Get output
+           id: get_output
+           run: |
+             DELIM="$(openssl rand -hex 8)"
+             echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+             cat build.md >> "$GITHUB_OUTPUT"
+             echo "${DELIM}" >> "$GITHUB_OUTPUT"
+             cp -f build.md build_rvxmt.tmp
+
+         - run: sleep 260
+
+         - name: Upload modules to release
+           uses: svenstaro/upload-release-action@v2
+           with:
+             body: ${{ steps.get_output.outputs.BUILD_LOG }}
+             repo_token: ${{ secrets.GITHUB_TOKEN }}
+             file: ./build/*
+             tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+             file_glob: true
+             overwrite: true
+
+         - name: Update changelog and Magisk update json
+           id: update_config
+           run: |
+             git checkout -f update || git switch --discard-changes --orphan update
+             cp -f build_rvxmt.tmp build_rvxmt.md
+             get_update_json() {
+               echo "{
+               \"version\": \"$1\",
+               \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+               \"zipUrl\": \"$2\",
+               \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build_rvxmt.md\"
+             }"
+             }
+
+             cd build || { echo "build folder not found"; exit 1; }
+             for OUTPUT in *magisk*.zip; do
+               [ "$OUTPUT" = "*magisk*.zip" ] && continue
+               ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+               if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+               UPDATE_JSON="${UPDATE_JSON##*/}"
+               VER=$(echo "$ZIP_S" | grep version=)
+               VER="${VER##*=}"
+               DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+               get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+             done
+             cd ..
+
+             find . -name "*-rvxmt-update.json" | grep . || : >dummy-update.json
+
+         - name: Update git
+           run: |
+             git fetch origin update
+             git pull origin update
+        
+         - uses: stefanzweifel/git-auto-commit-action@v5
+           with:
+            branch: update
+            skip_fetch: false
+            skip_checkout: false
+            file_pattern: build_rvxmt.md *-rvxmt-update.json
+            commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
  build_rvx_reddit:
    runs-on: ubuntu-latest
    steps:
